export const SCHOOLS = [
  'University of Ghana (UG)',
  'Kwame Nkrumah University of Science and Technology (KNUST)',
  'University of Cape Coast (UCC)',
  'University of Education, Winneba (UEW)',
  'University of Professional Studies, Accra (UPSA)',
  'Ghana Institute of Management and Public Administration (GIMPA)',
  'University of Health and Allied Sciences (UHAS)',
  'University for Development Studies (UDS)',
  'Ashesi University',
  'Central University',
  'Valley View University',
  'Presbyterian University College, Ghana',
  'Methodist University Ghana',
  'Ghana Communication Technology University (GCTU)',
  'Accra Technical University',
  'Kumasi Technical University',
  'Ho Technical University',
  'Takoradi Technical University',
  'Ghana Institute of Journalism (GIJ)',
  'Wisconsin International University College',
  'Other',
];
