export const SCHOOLS = [
  'University of Lagos (UNILAG)',
  'University of Ibadan (UI)',
  'Obafemi Awolowo University (OAU)',
  'University of Nigeria, Nsukka (UNN)',
  'Ahmadu Bello University (ABU)',
  'University of Benin (UNIBEN)',
  'Lagos State University (LASU)',
  'Yaba College of Technology (YABATECH)',
  'Federal University of Technology, Akure (FUTA)',
  'Covenant University',
  'Babcock University',
  'Pan-Atlantic University',
  'American University of Nigeria (AUN)',
  'Nile University',
  'University of Abuja',
  'University of Port Harcourt (UNIPORT)',
  'Rivers State University (RSU)',
  'Delta State University (DELSU)',
  'University of Ilorin (UNILORIN)',
  'Kwara State University (KWASU)',
  'Other',
];
